### ISSUE TITLE
Editor Scale field doesn't use value

### ISSUE THREAD

**Issue by Jugglernaut** [Ikeiwa/3D-beatsaber-song-editor#3]
![image](https://user-images.githubusercontent.com/1657530/39791860-6057fb0c-5303-11e8-9204-0a70fe35e0e9.png)

When I try to put in a new value, on hitting enter or selecting another field the value just reverts to 200. I am able to edit the other fields as expected.

**Comment by Ikeiwa** [comment]
you can't change the scale under 200 it only works with bigger values.
